baseURL = "https://unknwon.io/"
title = "UNKNWON"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "landofunknown"

[params]
    # author = "Unknwon"
    info = "Life is magic. Coding is art."
    description = "Unknwon's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "https://avatars2.githubusercontent.com/u/2946214?s=460&v=4"

    favicon_32 = "/img/favicon.png"
    favicon_16 = "/img/favicon.png"

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = ["css/custom.css"]

[[params.social]]
    name = "GitHub"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/unknwon"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/jc_unknwon"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/jiahua-chen-86218a81/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"